### ISSUE TITLE
Modals are misaligned

### ISSUE THREAD

**Issue by MvanDuuren** [nk-crew/ghostkit#145]
Hi,

Since Wordpress 5.9, all of Ghostkits modals (templates, styles, etc.) are misaligned and thus unusable.

![image](https://user-images.githubusercontent.com/11379255/152352888-ff16ca99-4a0f-4155-92df-fe10313be6c0.png)

**Comment by nk-o** [comment]
Please, wait for the plugin update, will be released soon.

Fixed in https://github.com/nk-crew/ghostkit/issues/142

**Comment by MvanDuuren** [comment]
> Please, wait for the plugin update, will be released soon.
> 
> Fixed in #142

Sorry, didn't see that issue. Thanks!
