### ISSUE TITLE
Youtube video no longer loads in the video block

### ISSUE THREAD

**Issue by Smid98** [nk-crew/ghostkit#147]
After updating to 2.22.2, a youtube video no longer loads in the video block on the front-end.

<img width="1372" alt="Screenshot 2022-02-15 at 17 20 46" src="https://user-images.githubusercontent.com/25586044/154103928-142e2676-7a9b-4848-844f-82647d210402.png">

**Comment by landportalua** [comment]
it happened on my site now on the new 3.1 vrsion (land.gov.ua on the bottom pf the page)
