### ISSUE TITLE
Table Of Contents not adding IDs to headings 

### ISSUE THREAD

**Issue by GabrielZalisz** [nk-crew/ghostkit#151]
In design mode, Table Of Contents Gutenberg Block nicely generates preview of the TOC. However, when viewing the page itself, no TOC is shown, unless I manually add anchor IDs to my Heading blocks using default Wordpress box on sidebar. Only the headings with manually edited #ids are then visible in TOC. It used to work properly when I first installed Ghostkit plugin a year ago.

**Comment by nk-o** [comment]
fixed in https://github.com/nk-crew/ghostkit/commit/10f4e339129b9c74ebb228b8639bc12beeb705db Please, wait for the plugin update
