### ISSUE TITLE
ghost kit grid background image

### ISSUE THREAD

**Issue by ellemaker** [nk-crew/ghostkit#167]
demo 
![image](https://user-images.githubusercontent.com/4677416/216985511-f9d7f454-e06f-4e81-8641-00e957ae338e.png)

in my site
![image](https://user-images.githubusercontent.com/4677416/216985639-615813e1-8638-4263-9d6b-81e0a435dc96.png)

not sure what to update; I need to put alt tags on that image

**Comment by nk-o** [comment]
Hey. You can add Alt to images in the Media Library. And then, once you insert the image in the Grid background, this Alt text will be added.

<img width="506" alt="Shot 2023-02-13 at 12 05 58" src="https://user-images.githubusercontent.com/14810891/218415893-6855a5a9-1f13-4ec5-b9df-805f33aabaf1.png">
