### ISSUE TITLE
button with icon right works till a link is set.

### ISSUE THREAD

**Issue by musicjunk** [nk-crew/ghostkit#171]
Hello, please test your button with icon right. everything looks great. When a link ist set the icon moves back to left an the css is not working right anymore. 
Thank you for this great plugin.

**Comment by nk-o** [comment]
Unfortunately, I can't reproduce this issue locally. Could you download the development build and check the button on a fresh installation? And in case this bug will be visible again, please, provide a step-by-step reproduction guide for us.

I will close this issue for now, let's look at it after the plugin will be updated.
