### ISSUE TITLE
Tabs no longer working in editor

### ISSUE THREAD

**Issue by eyetractive** [nk-crew/ghostkit#172]
Since updating to WordPress 6.3, I have observed the following behavior:

1. Tabs are not clickable in the editor anymore, so I cannot switch to any tab other than the first. Clicking a tab only selects the tab's name as a text input, no console errors are logged.
2. Adding and deleting a tab works, but when deleting a tab, the button to confirm is invisible (but clickable).

The front-end appears to be unaffected and work as intended.

[https://imgur.com/a/1fdmVlm](https://imgur.com/a/1fdmVlm)

**Comment by nk-o** [comment]
1. I think it is fixed already in this commit - https://github.com/nk-crew/ghostkit/commit/5a8932e0cb2c1f6c6b3e5a78e55cf776f897c6f4. It will be a part of the next huge plugin update. Currently you can try to use the development build.
2. Fixed already in this commit - https://github.com/nk-crew/ghostkit/commit/4004d0f5ab40f26bf7f9e6bbde1db0d9c8731e07

**Comment by eyetractive** [comment]
Thank you. I can confirm that the development build fixes this issue.
