### ISSUE TITLE
Version control templates

### ISSUE THREAD

**Issue by traed** [nk-crew/ghostkit#88]
When building a custom theme for a customer it would be great if we could create templates on in our test environment and then have them version controlled together with the theme. That way we could just pull the latest changes with the rest of the code and not have to manually export and import them.

Is there a way to do this at this time? #25 seems to mention this but I can't find any documentation?

Advanced Custom Fields does this by saving a json-config-file in a special directory in the active theme for each field group created. Maybe ghostkit could do something similar?

**Comment by nk-o** [comment]
I don't think that synchronization will be added, but exporting/importing is a good feature, that we need to add in future updates.
